In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.special as special
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [39]:
from google.colab import files
files.upload()
#Cargar desde un archivo .csv sin indice
df=pd.read_csv('microretailer_mit_lift_lab_limpio(3).csv')

Saving microretailer_mit_lift_lab_limpio(3).csv to microretailer_mit_lift_lab_limpio(3) (1).csv


In [3]:
#Rellenamos nulos 
df=df.fillna(method="ffill")


In [18]:
#corroboramos valores nulos 
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                              0
_record_id                              0
_title                                  0
_server_updated_at                      0
_updated_by                             0
                                       ..
234_willingness_participate_workshop    0
318_shopkeeper_name                     0
319_shopkeepers_last_name               0
236_whatsapp                            0
235_email                               0
Length: 107, dtype: int64

In [19]:
#Declaramos variables dependientes e independientes para la regresion logistica 
Vars_Indep=df[['97_number_of_customers_in_store', '268_number_fridges', '104_how_many_shelves_does_the_micro_retailer_have']]
Var_Dep=df['102_does_the_micro_retailer_sells_fresh_products_']

In [6]:
#Redefinimos la variable 
X=Vars_Indep
y=Var_Dep

In [7]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=None)

In [8]:
#Se escalan datos
escalar=StandardScaler()

In [9]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueva utilizaremos fit_transform
x_train=escalar.fit_transform(x_train)
X_test=escalar.transform(x_test)

In [10]:
#Define el algoritmo a autilizar 
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

In [11]:
#entrenamos el modelo 
algoritmo.fit(x_train,y_train)

LogisticRegression()

In [12]:
#Relizamos una prediccion
y_prend=algoritmo.predict(X_test)
y_prend

array(['no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no'], dtype=object)

In [13]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_prend)
print('Matriz de confusion')
print(matriz)

Matriz de confusion
[[28  3]
 [15  4]]


In [15]:
#calculo de la presision del modelo 
from sklearn.metrics import precision_score
presicion=precision_score(y_test,y_prend,average="binary",pos_label="yes")
print('Presicion del modelo:')
print(presicion)

Presicion del modelo:
0.5714285714285714


In [16]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import accuracy_score

Exactitud=accuracy_score(y_test,y_prend)
print('Exactitud del modelo:')
print(Exactitud)

Exactitud del modelo:
0.64


In [17]:
#calculo de la presision del modelo (recall_score) 
#Calcul de la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_prend,average="binary",pos_label="yes")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.21052631578947367


**CASO 2**

In [63]:
#Declaramos variables dependientes e independientes para la regresion logistica 
Vars_Indep=df[['_latitude', '_longitude', '104_how_many_shelves_does_the_micro_retailer_have']]
Var_Dep=df['99_does_the_micro_retailer_exhibits_products_outside_']

In [64]:
#Redefinimos la variable 
X=Vars_Indep
y=Var_Dep

In [65]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=None)

In [66]:
#Se escalan datos
escalar1=StandardScaler()

In [67]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueva utilizaremos fit_transform
x_train=escalar1.fit_transform(x_train)
X_test=escalar1.transform(x_test)

In [68]:
#Define el algoritmo a autilizar 
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

In [69]:
#entrenamos el modelo 
algoritmo.fit(x_train,y_train)

LogisticRegression()

In [70]:
#Relizamos una prediccion
y_prend=algoritmo.predict(X_test)
y_prend

array(['no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'yes', 'no'], dtype=object)

In [71]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_prend)
print('Matriz de confusion')
print(matriz)

Matriz de confusion
[[56  2]
 [23  2]]


In [72]:
#calculo de la presision del modelo 
from sklearn.metrics import precision_score
presicion=precision_score(y_test,y_prend,average="binary",pos_label="yes")
print('Presicion del modelo:')
print(presicion)

Presicion del modelo:
0.5


In [73]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import accuracy_score

Exactitud=accuracy_score(y_test,y_prend)
print('Exactitud del modelo:')
print(Exactitud)

Exactitud del modelo:
0.6987951807228916


In [74]:
#calculo de la presision del modelo (recall_score) 
#Calcul de la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_prend,average="binary",pos_label="yes")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.08


**CASO 3**

In [75]:
#Declaramos variables dependientes e independientes para la regresion logistica 
Vars_Indep=df[['145_number_direct_competitors', '24_burnout', '104_how_many_shelves_does_the_micro_retailer_have']]
Var_Dep=df['le_comento_que_toda_esta_informacin_es_confidencial']

In [76]:
#Redefinimos la variable 
X=Vars_Indep
y=Var_Dep

In [77]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=None)

In [78]:
#Se escalan datos
escalar2=StandardScaler()

In [79]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueva utilizaremos fit_transform
x_train=escalar2.fit_transform(x_train)
X_test=escalar2.transform(x_test)

In [80]:
#Define el algoritmo a autilizar 
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

In [81]:
#entrenamos el modelo 
algoritmo.fit(x_train,y_train)

LogisticRegression()

In [82]:
#Relizamos una prediccion
y_prend=algoritmo.predict(X_test)
y_prend

array(['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes'], dtype=object)

In [83]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_prend)
print('Matriz de confusion')
print(matriz)

Matriz de confusion
[[ 0  3]
 [ 0 64]]


In [84]:
#calculo de la presision del modelo 
from sklearn.metrics import precision_score
presicion=precision_score(y_test,y_prend,average="binary",pos_label="yes")
print('Presicion del modelo:')
print(presicion)

Presicion del modelo:
0.9552238805970149


In [86]:
#calculo de la presision del modelo (recall_score) 
#Calcul de la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_prend,average="binary",pos_label="yes")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0
